export const USER = {
  AUTH: "AUTH",
  AUTHERR: "AUTHERR"
};

export const DOCTOR = {
  RECOMMENDED: "RECOMMENDED",
  LOADERR: "LOADERR"
};

export const SECTION = {
  GETSECTIONS: "GETSECTIONS",
  LOADERR: "LOADERR"
};
