export const USER = {
  AUTH: "AUTH",
  AUTHERR: "AUTHERR"
};

export const DOCTOR = {
  RECOMMENDED: "RECOMMENDED",
  LOADERR: "LOADERR"
};

export const SECTION = {
  GETSECTIONS: "GETSECTIONS",
  LOADDOCTORS: "LOADDOCTORS",
  LOADERR: "LOADERR"
};

export const FORM = {
  BLUR: "BLUR",
  VALIDATE: "VALIDATE"
};

export const POST = {
  GETPOSTS: "GETPOSTS",
  ADDPOST: "ADDPOST",
  LOADERR: "LOADERR",
  VOTE: "VOTE"
};

export const COMMENT = {
  GETCOMMENTS: "GETCOMMENTS",
  NEWCOMMENT: "NEWCOMMENT",
  LOADERR: "LOADERR"
};

export const CHAT = {
  GETALLCHATS: "GETALLCHATS",
  SEND: "SEND",
  LOADERR: "LOADERR"
};

export const PROFILE = {
  GET: "GET",
  LOADERR: "LOADERR"
};

export const APPOINTMENT = {
  GET: "GET",
  RESERVE: "RESERVE",
  LOADERR: "LOADERR"
}